name: ci

on:
  push:
   branches:
    - feature/workflows
    - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/open-feature/golang-sdk-contrib
      GOBIN: /home/runner/work/open-feature/golang-sdk-contrib/bin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.18.1'
      - run: make workspace-init
      - run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/open-feature/golang-sdk-contrib
      GOBIN: /home/runner/work/open-feature/golang-sdk-contrib/bin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.18.1' 
      - run: make workspace-init
      - run: make test